### ISSUE TITLE
Rafiki: Mock Account Provider UI

### ISSUE THREAD

**Issue by matdehaast** [interledger/roadmap#23]
## Summary

The mock account provider (MAP) keeps account data for the account provider in memory. These will be difficult to see without an UI. The goal is to provide a basic UI to see balances and accounts as if it were an account provider.

## Intended Outcomes
- UI to select different accounts within the account provider
- See the balance and transactions for an account within the UI

## How will it work?

A user can go to the URL of the MAP application running an be able to select and see detailed information of the various accounts that it has.

## Links

- https://github.com/interledger/rafiki/issues/717

**Comment by mkurapov** [comment]
Balances are now being shown after https://github.com/interledger/rafiki/pull/694 was merged. 
Transactions, however, are not just yet
