### ISSUE TITLE
Rafiki: Admin UI - Payment Pointers, Events & Liquidity Management

### ISSUE THREAD

**Issue by sabineschaller** [interledger/roadmap#30]
## Summary
Add additional views / options to Admin UI

## Intended Outcomes

- [x] Admin can view events
- [x] Admin can create payment pointers
- [ ] ~~Admin can deposit and withdraw liquidity given events~~

## How will it work?
- TODO: designs

**Comment by mkurapov** [comment]
Before we do the 3rd task, we should consider changing how we manage liquidity for events: 
- https://github.com/interledger/rafiki/issues/1521

**Comment by sabineschaller** [comment]
Since we are moving away from event liquidity in the future, this can be considered done.
