### ISSUE TITLE
Rafiki: Spring Cleanup

### ISSUE THREAD

**Issue by sabineschaller** [interledger/roadmap#31]
## Summary
Add miscellaneous features and refactoring

## Intended Outcomes
- reduce number of open issues in the Rafiki repo

## Links
- https://github.com/interledger/rafiki/issues

**Comment by mkurapov** [comment]
Created [Tech Debt Milestone](https://github.com/interledger/rafiki/milestone/13), worked on a few issues related to that.
Mostly pivoted to writing features for alpha v1, v2, v3 rafiki release.
